### ISSUE TITLE
【创建账户】创建钱包账户时，验证码超时提示非中文且验证码不会自动刷新

### ISSUE THREAD

**Issue by lyyhitl2018** [CybexDex/cybex-web#59]
创建云钱包账户时，验证码超时提示为英文，未翻译，并且验证码不会自动刷新，用户不知道验证码什么时候过期

**Comment by Megan-TA** [comment]
超时自动刷新验证码目测现在没有其他web实现此类功能，超时了提交会失败自动刷新验证码
